version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/request-context

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run build
      - run: npm test

  build_and_publish:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/request-context

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm audit
      - run: npm run build
      - run: npm test

      - run:
          name: Publish the package to npm private registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm config set scope @jamessawle
            npm publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: node-library
          filters:
            tags:
              ignore: /^v.*/
  build_and_publish:
    jobs:
      - build_and_publish:
          context: node-library
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
