version: 2
jobs:
  build_feature:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/jwt-authentication

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm test
      - run: npm start build

  build_and_publish:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/jwt-authentication

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm audit
      - run: npm test
      - run: npm start build

      - run:
          name: Publish the package to npm private registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm config set scope @rightmove
            npm publish

workflows:
  version: 2
  build_feature_branch:
    jobs:
      - build_feature:
          context: node-library
          filters:
            branches:
              ignore: master
  build_master:
    jobs:
      - build_and_publish:
          context: node-library
          filters:
            branches:
              only: master
